# Generated by Django 3.2.9 on 2021-11-29 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_volume', models.IntegerField(verbose_name='Total volume')),
                ('total_bags', models.IntegerField(verbose_name='Total bags')),
                ('small_bags', models.IntegerField(verbose_name='Small bags')),
                ('large_bags', models.IntegerField(verbose_name='Large bags')),
                ('xl_bags', models.IntegerField(verbose_name='Extra large bags')),
                ('type', models.CharField(max_length=50, verbose_name='Type')),
                ('year', models.IntegerField(verbose_name='Year')),
                ('region', models.CharField(max_length=50, verbose_name='Region')),
            ],
        ),
    ]
