# Generated by Django 3.2.9 on 2021-12-02 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0002_auto_20211129_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictioninput',
            name='val_one',
        ),
        migrations.RemoveField(
            model_name='predictioninput',
            name='val_three',
        ),
        migrations.RemoveField(
            model_name='predictioninput',
            name='val_two',
        ),
        migrations.AddField(
            model_name='predictioninput',
            name='large_avo',
            field=models.FloatField(default=0, verbose_name='Large avocados'),
        ),
        migrations.AddField(
            model_name='predictioninput',
            name='small_avo',
            field=models.FloatField(default=0, verbose_name='Small avocados'),
        ),
        migrations.AddField(
            model_name='predictioninput',
            name='xl_avo',
            field=models.FloatField(default=0, verbose_name='Extra large avocados'),
        ),
    ]
