# Generated by Django 3.2.9 on 2021-12-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0003_auto_20211202_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictioninput',
            name='type',
            field=models.CharField(choices=[('ORG', 'organic'), ('CON', 'conventional')], default='CON', max_length=3, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='predictioninput',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Year'),
        ),
    ]
