# Generated by Django 3.2.9 on 2021-12-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0005_alter_predictioninput_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictioninput',
            name='year',
            field=models.PositiveIntegerField(default=0, verbose_name='Year'),
        ),
    ]
