# Generated by Django 3.2.9 on 2021-12-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0006_alter_predictioninput_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictioninput',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Year'),
        ),
    ]
