# Generated by Django 3.2.9 on 2021-12-07 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0010_auto_20211205_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predictioninput',
            name='type',
        ),
    ]
