# Generated by Django 3.2.9 on 2021-12-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0011_remove_predictioninput_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictioninput',
            name='type',
            field=models.CharField(choices=[('1', 'Organic'), ('2', 'Conventional')], default='1', max_length=3, verbose_name='Type'),
            preserve_default=False,
        ),
    ]
