# Generated by Django 3.2.9 on 2021-12-07 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('predictor', '0012_predictioninput_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predictioninput',
            name='type',
            field=models.CharField(choices=[('ORG', 'Organic'), ('CON', 'Conventional')], max_length=3, verbose_name='Type'),
        ),
    ]
